EXTRN BALL_X:WORD
EXTRN BALL_Y:WORD
EXTRN BALL_VELOCITY_X:WORD
EXTRN BALL_VELOCITY_Y:WORD

PUBLIC moveBall

.MODEL SMALL
.STACK 100h

.CODE
moveBall PROC FAR
MOV AX,BALL_VELOCITY_X
ADD BALL_X,AX           ;move x-axis
MOV AX,BALL_VELOCITY_Y
ADD BALL_Y,AX             ;move y-axis
RET
moveBall ENDP
END